server:
  port: 8181

spring:
  application:
    name: limits-app
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres?currentSchema=limits_schema
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  sql:
    init.mode: always

limits:
  day-value: 10000.00
  user-count: 100

cron:
  expression: 0 0 0 * * *
  zone: Asia/Krasnoyarsk

